#%RAML 1.0
title: Employee Management API
version: v1
baseUri: https://api.company.com/v1
mediaType: application/json

protocols:
  - HTTP
  - HTTPS

uses:
  employeeType: datatype/employee.raml
  
/employees:
  post:
    description: Create a new employee
    body:
      type: employeeType.Employee  
      example: !include example/employeeBody.json
    responses:
      201:
        body:
          application/json:
            example: !include example/empCreated.json
  /{id}:
    uriParameters:
      id: 
        type: integer
    get:
      description: Get details of a specific employee by ID
      responses:
        200:
          body:
            application/json:
              example: !include example/employeeBody.json
        404:
          description: Employee not found
          body:
            application/json:
              example: !include example/notFoundResponse.json

    put:
      description: Update details of a specific employee
      body:
        type: employeeType.EmployeeUpdate  # Referencing the imported type
        example: !include example/employeeBody.json
      responses:
        200:
          body:
            example: !include example/updateResponse.json
        404:
          description: Employee not found
          body:
            example: !include example/notFoundResponse.json

    delete:
      description: Delete a specific employee by ID
      responses:
        201:
          description: Successfully deleted
        404:
          description: Employee not found
          body:
            example: !include example/notFoundResponse.json
